### PR TITLE
fix(autoassign): narrow custom escalation teams to requested org

### LINKED ISSUE #54: Autoassign fails if another org has custom escalation conversations available
**Describe the bug**
If a texter is a member of a custom escalation team in another organization (Org B) and that team has replies available, they will not be able to get assigned texts in their current organization (Org A)

**To Reproduce**

1.  Assign a texter to a team for replies in Org A and a team for custom escalation replies in Org B (on the same instance
2.  Enable the replies form for Org A (and have replies available)
3.  Enable the custom escalation form for Org B (and have replies available)
4.  Request texts in Org A
5.  Observe that texts will not be assigned to the texter in Org A

**Expected behavior**
Assign replies from Org A to the texter

**Additional context**
Autoassign prioritizes custom escalation teams intentionally, as these are the most "important" replies for the texter to work on. However, autoassign should _not_ ever consider teams from outside the requested organization as an available option

### PR DESCRIPTION
**Pull request by ajohn25**
## Description

This limits the scope of custom escalation teams considered for autoassigment so that only teams in the organization where the texter requests texts are considered. Specifically:

- Fetch `team_assignment_options` via an easier to read query
- Join to `team_assignment_options` when fetching the tags to consider for custom escalation teams (so only teams in the organization where texts were requested are considered)

## Motivation and Context

Closes #54 

## How Has This Been Tested?

This has been tested locally

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have included updates for the documentation accordingly.

### CODE REVIEW

File: src/server/api/assignment.js [hunk 1]
```diff
@@ -594,26 +594,16 @@ export async function myCurrentAssignmentTargets(
...
-        from team_escalation_tags
-        where exists (
-          select 1
-          from user_team
-          where user_team.team_id = team_escalation_tags.team_id
-            and user_id = ?
-        )
+        select array_agg(esc.tag_id) as my_escalation_tags
+        from team_escalation_tags esc
+        join team_assignment_options opts on esc.team_id = opts.id
```
Comment (sukhada) [inline src/server/api/assignment.js:606]: should this be a left join?

**Review by sukhada — APPROVED** [review]

File: src/server/api/assignment.js (hunk 1 above)
Comment (ajohn25) [reply src/server/api/assignment.js:606]: I think intentional inner join here. With a left join, I believe all values for the column `team_escalation_tags.tag_id` would get returned in the `array_agg(esc.tag_id)`. With the inner join, we get tag ids with the filtering applied to `team_assignment_options`) (organization id, user id and assigment enabled), which I think is what we want to ensure what gets considered for assignment, is what's been requested by the texter
